### ISSUE TITLE
Fix links to pages to include complete scheme + domain name

### ISSUE THREAD

**Issue by migurski** [codeforamerica/city-analytics-dashboard#25]
Report from a user:

> As it works now, when I click on a page listed in one of the columns, it opens a separate window but truncates or main url.  For example, instead of going to http://www.example.org/employment, it goes to /employment.  Is there a part of the setup that I missed or is this how it works?

**Comment by phae** [comment]
I think it might be a bit missed. I think it's because the domain needs to be set in the root of the app. Will check.

**Comment by boonrs** [comment]
We deployed this for [City of Boulder](https://boulder-colorado.herokuapp.com/) and are seeing the same issue. When I take a look at the environment variables, GA_WEBSITE_URL is set correctly to the domain.

**Comment by rpringle** [comment]
I fixed this in Boulder's instance by hard-coding the domain into the index.html template. It looks like the content.js file needs to have the domain defined as a var under content.pages.push (line 18) but I'm unsure of where to parse it from. I don't know if it's part of the response from the endpoint call or not.

**Comment by phae** [comment]
Hmm. It may be a value that ought to be collected during the setup-app process. @migurski?

**Comment by rpringle** [comment]
Hi @phae, can you re-open this issue since my fix didn't work across both of our instances? Technically it's still broken for us (I fixed in our Heroku instance but it's basically a fork at this point).

**Comment by phae** [comment]
Sorry! Thought I had done!

**Comment by rpringle** [comment]
No worries, thanks!
